application/urls.py
from django.urls import path

from application.views import OrderListView, OrderDeleteView, ConfirmationView

urlpatterns = [
    path("orders/", OrderListView.as_view(), name="order-list"),
    path(
        "orders/<int:pk>/delete/",
        OrderDeleteView.as_view(),
        name="order-delete"
    ),
    path(
        "orders/deleted/",
        ConfirmationView.as_view(),
        name="order-confirm-delete"
    ),
]


app_name = "application"

producer_consumer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("application.urls", namespace="application")),
    path("accounts/", include("django.contrib.auth.urls")),
]

application/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class Employee(AbstractUser):
    position = models.CharField(max_length=64)
    probation = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} ({self.position})"


class Order(models.Model):
    task_id = models.IntegerField()
    name = models.CharField(max_length=64)
    description = models.TextField()
    employee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="orders"
    )

    def __str__(self):
        return f"{self.task_id} - {self.name}"

application/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.views import generic

from application.models import Order


class OrderListView(LoginRequiredMixin, generic.ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(employee=self.request.user)


class OrderDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Order

    def post(self, request, *args, **kwargs):
        if request.POST.get("confirm_delete") == "True":
            order = self.get_object()
            time = datetime.datetime.now()
            employee = order.employee
            context = {
                "id": order.id,
                "task_id": order.task_id,
                "name": order.name,
                "employee": f"{employee.first_name} ({employee.position})",
                "time": time,
            }
            order.delete()

            return render(
                request,
                "application/order_delete_info.html",
                context
            )

        return redirect("order-list")


class ConfirmationView(LoginRequiredMixin, generic.TemplateView):
    template_name = "application/order_delete_info.html"

templates/application/order_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <section class="mt-5 mt-lg-0 bg-soft d-flex align-items-center">
    <div class="container">
      <div class="row justify-content-center form-bg-image">
        <div class="col-12 d-flex align-items-center justify-content-center">
          <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
            <div class="text-center text-md-center mb-4 mt-md-0">
              <p><strong>
                  Task #{{ id }}-{{ task_id }} with name {{ name }}
                  was solved by {{ employee }} at {{ time }}
              </strong></p>
            </div>

            <div class="d-flex justify-content-center my-4">
              <a class="btn btn-info" href="{% url 'application:order-list' %}">Return to all orders</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/application/order_delete_info.html
{% extends "base.html" %}

{% block content %}
  <section class="mt-5 mt-lg-0 bg-soft d-flex align-items-center">
    <div class="container">
      <div class="row justify-content-center form-bg-image">
        <div class="col-12 d-flex align-items-center justify-content-center">
          <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
            <div class="text-center text-md-center mb-4 mt-md-0">
              <p><strong>
                  Task #{{ id }}-{{ task_id }} with name {{ name }}
                  was solved by {{ employee }} at {{ time }}
              </strong></p>
            </div>

            <div class="d-flex justify-content-center my-4">
              <a class="btn btn-info" href="{% url 'application:order-list' %}">Return to all orders</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/application/order_list.html
{% extends "base.html" %}

{% block content %}
  <a style="float: right" href="{% url 'logout' %}" class="btn btn-success">
    <span class="sidebar-text">Logout</span>
  </a>
  <br><br>

  {% if order_list %}
    <div class="card card-body border-0 shadow table-wrapper table-responsive">
      <table class="table table-hover">
        <thead>
        <tr>
          <th class="border-gray-200">Orders</th>
          <th class="border-gray-200"></th>
        </tr>
        </thead>

        <tbody>
        {% for order in order_list %}
          <tr>
            <td>
              <span class="fw-normal">{{ order.task_id }} {{ order.name }}</span>
            </td>
            <td>
              <form method="post" action="{% url 'application:order-delete' pk=order.id %}" class="mt-4">
                {% csrf_token %}
                  <input type="hidden" name="confirm_delete" value="True">
                  <input type="submit" value="🗑️">
              </form>
            </td>
          </tr>
       {% endfor %}
       </tbody>
      </table>
    </div>
  {% else %}
    <div class="container">
      <div class="row justify-content-center form-bg-image">
        <div class="col-12 d-flex align-items-center justify-content-center">
          <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
            <div class="text-center text-md-center mb-4 mt-md-0">
              <p><strong>
                  There are no orders for you!
              </strong></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Producer - Consumer</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous">
</head>

<body>
<div class="container-fluid for_footer">
  <div class="row">
    <div class="col-sm-12">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>
</body>
</html>